### ISSUE TITLE
சுரரைநீ - ஈரசைச்சீரா மூவசைச்சீரா?

### ISSUE THREAD

**Issue by kalarani** [virtualvinodh/avalokitam#1]
அவலோகிதம் தளத்தில் "சுரரைநீ" ஈரசைச்சீராகக்கொள்ளப்பட்டுள்ளது.

> சுர - நிரை | ரைநீ - நிரை

என பிரிக்கப்பட்டுள்ளது.
இதில் "ரைநீ" என்பது இரு நெடில்களைக்கொண்டுள்ளது. எனவே, 

> சுர - நிரை | ரை - நேர் | நீ - நேர்

என பிரிக்கப்படவேண்டும் என்று நினைக்கிறேன்.

**Comment by virtualvinodh** [comment]
Hi Kalarani,

'rai' is classified as 'Aikaarakurukkam' (any 'ai' that occurs dependently is classified as such) and hence for metrical purposes becomes a short vowel (kuril).  Hence, the analysis.

V
