### ISSUE TITLE
Hosted site is not on https

### ISSUE THREAD

**Issue by carun** [virtualvinodh/avalokitam#3]
https://www.avalokitam.com/analyzer doesn't work whereas http://www.avalokitam.com/analyzer does.

Browsers these days default to https. So please upgrade the site to use TLS.

**Comment by virtualvinodh** [comment]
Fixed. The site now uses https

Both https://www.avalokitam.com & https://avalokitam.com should work

**Comment by carun** [comment]
Thanks for this wonderful app!
